class AddLearns < ActiveRecord::Migration[5.1]
  def change
  	Learn.create :quote => "Le seul homme à ne jamais faire d'erreurs est celui qui ne fait rien.", :author_id => '1'
  	Learn.create :quote => "J'ai appris que le courage n'est pas l'absence de peur, mais la capacité de la vaincre.", :author_id => '2'
  	Learn.create :quote => "Une personne qui n'a jamais commis d'erreur n'a jamais tenté d'inover.", :author_id => '3'
  	Learn.create :quote => "La véritable indulgence consiste à comprendre et à pardonner les fautes qu'on ne serait pas capable de commettre.", :author_id => '4'
  	Learn.create :quote => "L'éducation c'est la famille qui la donne; l'instruction c'est l'Etat qui la doit.", :author_id => '4'
  	Learn.create :quote => "Rien ne nous trompe autant que notre jugement.", :author_id => '5'
  	Learn.create :quote => "La rigueur vient toujours à bout de l'obstacle.", :author_id => '5'
  	Learn.create :quote => "Qui pense peu, se trompe beaucoup.", :author_id => '5'
  	Learn.create :quote => "E=mc²", :author_id => '3'
  	Learn.create :quote => "Le désordre des êtres est dans l'ordre des choses.", :author_id => '6'
  	Learn.create :quote => "Plus tard ce sera trop tard. Notre vie c'est maintenant.", :author_id => '6'
  	Learn.create :quote => "Il n'y a pas six ou sept merveilles dans le monde, il n'y en a qu'une: c'est l'amour.", :author_id => '6'
  	Learn.create :quote => "Je n'avance pas vite, mais je ne recule jamais.", :author_id => '7'
  	Learn.create :quote => "La couleur est mon obsession quotidienne, ma joie et mon tourment.", :author_id => '8'
  	Learn.create :quote => "Créer, c'est donner une forme à son destin.", :author_id => '9'
  	Learn.create :quote => "Devenez le changement que vous voulez voir dans le monde.", :author_id => '10'
  	Learn.create :quote => "Donnez-moi un point fixe et un levier et je soulèverai la Terre.", :author_id => '11'
  	Learn.create :quote => "Je ne suis ni Athénien, ni Grec, mais un citoyen du monde.", :author_id => '12'
  	Learn.create :quote => "Il n'y a point de travail honteux.", :author_id => '12'
  	Learn.create :quote => "La beauté n'est la plupart du temps que la simplicité.", :author_id => '13'
  	Learn.create :quote => "Il est grand temps de rallumer les étoiles.", :author_id => '13'
  	Learn.create :quote => "Ce sont nos actes, nos décisions ou nos hésitations qui révèlent ce que nous sommes.", :author_id => '14'
  	Learn.create :quote => "Rien n'est jamais fini, il suffit d'un peu de bonheur pour que tout recommence.", :author_id => '15'
  	Learn.create :quote => "Tout le monde est un génie. Mais si vous jugez un poisson sur sa capacité à grimper à un arbre, il passera sa vie à croire qu'il est stupide.", :author_id => '3'
  	Learn.create :quote => "Il n'y a pas d'échec il n'y a que des abandons.", :author_id => '3'
  	Learn.create :quote => "L'art, mes enfants, c'est d'être absolument soi-même.", :author_id => '16'
  	Learn.create :quote => "I have a dream.", :author_id => '17'
  	Learn.create :quote => "Ne comptez pas les jours. Faites que chaque jour compte.", :author_id => '18'
  end
end
